<a href="https://colab.research.google.com/github/pradeepgrp/SpringBoard/blob/main/DataSplittingPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Splitting in Python

## First import the data set we'll use.

In [1]:
import pandas as pd

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("camnugent/california-housing-prices")

Downloading from https://www.kaggle.com/api/v1/datasets/download/camnugent/california-housing-prices?dataset_version_number=1...

100%|██████████| 400k/400k [00:00<00:00, 51.1MB/s]

Extracting files...

In [5]:
ca_housing = pd.read_csv('/content/housing.csv')

In [6]:
ca_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

## Create X dataframe with predictor variables and y dataframe with outcome variable

### Choose predictor variables by index location and concatenate

In [16]:
df1 = ca_housing.iloc[:,:-2]
df2 = ca_housing.iloc[:,-1:]

X = pd.concat ([df1,df2], axis=1)
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND

### Choose outcome variable by column name

In [18]:
y = ca_housing["median_house_value"]
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

## Use Scikit-learn to split the data

In [19]:
from sklearn.model_selection import train_test_split
train_test_split (X, y, test_size = 0.2)  #the results will appear in the output

[       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 11219    -117.90     33.80                21.0       1342.0           326.0
 9821     -121.92     36.62                52.0        867.0           199.0
 20637    -121.22     39.43                17.0       2254.0           485.0
 14964    -116.99     32.76                21.0       3833.0           595.0
 19811    -118.86     36.41                20.0       2749.0           575.0
 ...          ...       ...                 ...          ...             ...
 9086     -118.19     34.65                33.0       1781.0           326.0
 19883    -119.19     36.34                33.0       2199.0           403.0
 18685    -121.83     37.02                22.0       1903.0           350.0
 14004    -116.94     34.40                20.0       6541.0          1401.0
 9498     -123.73     39.17                20.0       4620.0          1042.0

        population  households  median_income ocean_proximity
 11219       748.0       335.0         2.9231       <1H OCEAN
 9821        391.0       187.0         2.6713      NEAR OCEAN
 20637      1007.0       433.0         1.7000          INLAND
 14964      1645.0       589.0         4.6250       <1H OCEAN
 19811      1195.0       491.0         3.0391          INLAND
 ...           ...         ...            ...             ...
 9086        913.0       314.0         3.9963          INLAND
 19883      1245.0       394.0         2.7300          INLAND
 18685       760.0       322.0         2.9559       <1H OCEAN
 14004      2631.0       980.0         2.1339          INLAND
 9498       1745.0       794.0         2.3750      NEAR OCEAN

 [16512 rows x 9 columns],
        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 16724    -120.66     35.47                18.0       2474.0           449.0
 16515    -121.22     37.80                37.0       1038.0           222.0
 7019     -118.09     33.97                35.0       2664.0           541.0
 4371     -118.28     34.11                52.0       1803.0           437.0
 20619    -121.56     39.01                22.0       1891.0           340.0
 ...          ...       ...                 ...          ...             ...
 12422    -116.23     33.71                17.0       4874.0          1349.0
 12404    -116.22     33.70                 9.0       3861.0           849.0
 5242     -118.40     34.11                32.0       5578.0           753.0
 6322     -117.98     33.99                26.0       3343.0           455.0
 9386     -122.45     37.90                30.0       3763.0           717.0

        population  households  median_income ocean_proximity
 16724      1269.0       431.0         3.9063       <1H OCEAN
 16515       521.0       211.0         2.1250          INLAND
 7019       2033.0       491.0         3.7326       <1H OCEAN
 4371        787.0       388.0         4.5781       <1H OCEAN
 20619      1023.0       296.0         2.7303          INLAND
 ...           ...         ...            ...             ...
 12422      5032.0      1243.0         2.4440          INLAND
 12404       825.0       401.0         3.2833          INLAND
 5242       1567.0       697.0        15.0001       <1H OCEAN
 6322       1429.0       457.0         7.0778       <1H OCEAN
 9386       1292.0       632.0         8.4888        NEAR BAY

 [4128 rows x 9 columns],
 11219     45000.0
 9821     234600.0
 20637     92300.0
 14964    273500.0
 19811    139700.0
            ...
 9086     126800.0
 19883     96900.0
 18685    288400.0
 14004     78500.0
 9498     158800.0
 Name: median_house_value, Length: 16512, dtype: float64,
 16724    184800.0
 16515     91900.0
 7019     164300.0
 4371     360500.0
 20619     99100.0
            ...
 12422     90000.0
 12404    124700.0
 5242     500001.0
 6322     334300.0
 9386     500001.0
 Name: median_house_value, Length: 4128, dtype: float64]

In [20]:
#Create variables to capture the output
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2)

### Add optional parameter to set a seed

In [21]:
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.2, random_state = 1337)